---

- hosts: dev 
  become: true 
  vars:
    ssh_key: ""
  vars_files:
    - vars/user.yml
  tasks:
  - name: create user
    user:
      name: "{{ user_name }}"
      password: "{{ user_password }}"
  
