---

- hosts: dev 
  become: true 
  tasks:
  - name: Install httpd on centos 7
    yum:
      name:
        - httpd
      update_cache: yes
    when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7' 

  - name: Install apache2 on debian
    apt:
      name:
        - apache2      
      update_cache: yes
    when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '22.04' 
  
  