---

- hosts: dev 
  become: true 
  tasks:
  - name: Install debian package
    apt:
      name:
        - apache2
        - git
      update_cache: yes
    when: ansible_os_family == 'Debian' 

  - name: Install RedHat package
    yum:
      name:
        - apache2
        - git
      update_cache: yes
    when: ansible_os_family == 'RedHat'  
  
  - name: debug ansible_os_family
    debug:
      var: ansible_facts['os_family']