---

- hosts: dev 
  become: true 
  tasks:
  - name: install apache2 and git
    apt:
      name: 
        - apache2
        - git
      update_cache: yes
  
  - name: change folder rights
    file:
      path: /var/www/html
      mode: '0755'
      state: directory
  
  - name: copy file 
    copy:
      src: html-ex1/
      dest: /var/www/html/

  - name: start apache2
    # module pour démarrer un service
    service:
      name: apache2
      state: started
      
