---

- hosts: dev 
  become: true 
  tasks:
  - name: get folder's files
    command: ls ./data
    register: files_list
  
  - name: display files
    debug:
      var: files_list.stdout_lines
  
  - name: save to local file
    become: false
    copy: 
      content: The content is {{ files_list.stdout_lines }}
      dest: localfile.txt
    delegate_to: localhost
  
  
  
      
