---

- hosts: dev # partie de l'inventory
  become: true # Execution en mode sudo sur la totalité des tasks
  # La Liste des taches à executer sur les clients
  tasks:
  - name: install git 
    apt:
      name: git
      update_cache: yes
  
  - name: install vim 
    apt:
      name: vim
      update_cache: yes
